# Site
name: "LocalData Lab"
title: "Local Data Lab"
description: "Seminario de periodismo de datos en el ámbito local."
logo: 'assets/images/logo.png'
favicon: 'assets/images/logo.png'
baseurl: ''
google_analytics: ''
disqus: ''
mailchimp-list: ''
include: ["_pages"]
permalink: /:title/

# Authors
authors:
  sal:
    name: Equipo
    display_name: Redacción
    web: https://localdatalab.umh.es/
    twitter: https://twitter.com/mipumh
    description: "Redacción del LocalDataLab."
  john:
    name: Equipo
    display_name: Redacción
    web: https://localdatalab.umh.es/
    twitter: https://twitter.com/PeriodismoUMH
    description: "Redacción del LocalDataLab."

# Plugins
plugins: 
  - jekyll-paginate
  - jekyll-sitemap
  - jekyll-feed
  - jekyll-seo-tag
  - jekyll-archives
    
# Archives
jekyll-archives:
  enabled:
    - categories
  layout: archive
  permalinks:
    category: '/category/:name/'
    
# Pagination 
paginate: 6
paginate_path: /page:num/
    
# Other
markdown: kramdown

kramdown:
  input: GFM
  syntax_highlighter: rouge
  syntax_highlighter_opts:
    block:
      line_numbers: true

# Adsense (change to "enabled" to activate, also your client id and ad slot. Create a new ad unit from your Adsense account to get the slot.)
adsense: "disabled"
adsense-data-ad-client: ""
adsense-data-ad-slot: ""

# Lazy Images ("enabled" or "disabled")
lazyimages: "enabled"