# Site
name: "LocalData Lab"
title: "Local Data Lab"
description: "Seminario de periodismo de datos en el ámbito local."
logo: 'assets/images/logo.png'
favicon: 'assets/images/logo.png'
baseurl: ''
disqus: ''
mailchimp-list: ''
include: ["_pages"]
permalink: /:title/

# Authors
authors:
  red:
    name: red
    display_name: LocalDataLab
    web: https://localdatalab.umh.es/
    pic: /assets/images/logo.png
    twitter: https://twitter.com/mipumh
    description: "Redacción del LocalDataLab."
  pedro:
    name: pedro
    display_name: Pedro Miguel González
    web: https://localdatalab.umh.es/
    pic: /assets/images/pedro.jpg
    twitter: https://petertecnologia.medium.com/
    description: "Redacción del LocalDataLab."
  irene:
    name: irene
    display_name: Irene C. Reig
    web: https://localdatalab.umh.es/
    pic: https://pbs.twimg.com/profile_images/1116261717074436096/rEe7H66D_400x400.png
    twitter: https://twitter.com/ReigCe
    description: "Redacción del LocalDataLab."
  felix:
    name: felix
    display_name: Félix Arias
    web: https://localdatalab.umh.es/
    pic: /assets/images/team/felix.jpg
    twitter: https://twitter.com/flxarias
    description: "Director del LocalDataLab."
  veronica:
    name: veronica
    display_name: Verónica Maciá
    web: https://localdatalab.umh.es/
    pic: https://pbs.twimg.com/profile_images/1119932529270824961/HC29SF_i_400x400.jpg
    twitter: https://twitter.com/VeronicaMaciaRi
    description: "Redacción del LocalDataLab."
  enrique:
    name: enrique
    display_name: Enrique Fernández
    web: https://localdatalab.umh.es/
    pic: https://pbs.twimg.com/profile_images/711564377703510016/NDLg5Q3J_400x400.jpg
    twitter: https://twitter.com/byhenry77
    description: "Redacción del LocalDataLab."
  gara:
    name: gara
    display_name: Gara Pulido
    web: https://localdatalab.umh.es/
    pic: https://pbs.twimg.com/profile_images/1007259645499592705/X8merZBo_400x400.jpg
    twitter: https://twitter.com/PulidoTacoronte
    description: "Redacción del LocalDataLab."

# Plugins
plugins: 
  - jekyll-paginate
  - jekyll-sitemap
  - jekyll-feed
  - jekyll-seo-tag
  - jekyll-archives
    
# Archives
jekyll-archives:
  enabled:
    - categories
  layout: archive
  permalinks:
    category: '/category/:name/'
    
# Pagination 
paginate: 12
paginate_path: /page:num/
    
# Other
markdown: kramdown

kramdown:
  math_engine: mathjax
  input: GFM
  syntax_highlighter: rouge
  syntax_highlighter_opts:
    block:
      line_numbers: true

# Adsense (change to "enabled" to activate, also your client id and ad slot. Create a new ad unit from your Adsense account to get the slot.)
adsense: "disabled"
adsense-data-ad-client: ""
adsense-data-ad-slot: ""

# Lazy Images ("enabled" or "disabled")
lazyimages: "enabled"