# Site
name: "LocalData Lab"
title: "Local Data Lab"
description: "Seminario de periodismo de datos en el ámbito local."
logo: 'assets/images/logo.png'
favicon: 'assets/images/logo.png'
baseurl: ''
google_analytics: 'UA-38906933-4'
disqus: ''
mailchimp-list: ''
include: ["_pages"]
permalink: /:title/

# Authors
authors:
  red:
    name: LocalDataLab
    display_name: LocalDataLab
    web: https://localdatalab.umh.es/
    pic: https://localdatalab.umh.es/assets/images/logo.png
    twitter: https://twitter.com/mipumh
    description: "Redacción del LocalDataLab."
  irene:
    name: irene
    display_name: Irene C. Reig
    web: https://localdatalab.umh.es/
    pic: https://pbs.twimg.com/profile_images/1116261717074436096/rEe7H66D_400x400.png
    twitter: https://twitter.com/ReigCe
    description: "Redacción del LocalDataLab."

# Plugins
plugins: 
  - jekyll-paginate
  - jekyll-sitemap
  - jekyll-feed
  - jekyll-seo-tag
  - jekyll-archives
    
# Archives
jekyll-archives:
  enabled:
    - categories
  layout: archive
  permalinks:
    category: '/category/:name/'
    
# Pagination 
paginate: 6
paginate_path: /page:num/
    
# Other
markdown: kramdown

kramdown:
  input: GFM
  syntax_highlighter: rouge
  syntax_highlighter_opts:
    block:
      line_numbers: true

# Adsense (change to "enabled" to activate, also your client id and ad slot. Create a new ad unit from your Adsense account to get the slot.)
adsense: "disabled"
adsense-data-ad-client: ""
adsense-data-ad-slot: ""

# Lazy Images ("enabled" or "disabled")
lazyimages: "enabled"